-- MySQL Script generated by MySQL Workbench
-- Fri Feb 14 13:00:42 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Escuela
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Escuela
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Escuela` DEFAULT CHARACTER SET utf8 ;
USE `Escuela` ;

-- -----------------------------------------------------
-- Table `Escuela`.`Alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escuela`.`Alumnos` (
  `alumnos_id` INT GENERATED ALWAYS AS () VIRTUAL,
  `nombre` VARCHAR(45) NULL,
  `aplellidos` VARCHAR(45) NULL,
  `fechaNacimiento` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`alumnos_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escuela`.`Asignaturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escuela`.`Asignaturas` (
  `asignatura_id` INT GENERATED ALWAYS AS () VIRTUAL,
  `horas_semana` TIME NOT NULL DEFAULT 02:00:00,
  `nombre` VARCHAR(45) NULL,
  `fecha_inicio` VARCHAR(45) NULL,
  PRIMARY KEY (`asignatura_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escuela`.`Departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escuela`.`Departamentos` (
  `deparamento_id` INT GENERATED ALWAYS AS () VIRTUAL,
  `director` INT NOT NULL,
  `profesor_id` INT NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`deparamento_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escuela`.`Profesores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escuela`.`Profesores` (
  `profesores_id` INT GENERATED ALWAYS AS () VIRTUAL,
  `nombre` VARCHAR(45) NULL,
  `aplellidos` VARCHAR(45) NULL,
  `fechaNacimiento` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `Departamentos_deparamento_id` INT NOT NULL,
  PRIMARY KEY (`profesores_id`, `Departamentos_deparamento_id`),
  INDEX `fk_Profesores_Departamentos1_idx` (`Departamentos_deparamento_id` ASC) VISIBLE,
  CONSTRAINT `fk_Profesores_Departamentos1`
    FOREIGN KEY (`Departamentos_deparamento_id`)
    REFERENCES `Escuela`.`Departamentos` (`deparamento_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escuela`.`Grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escuela`.`Grupos` (
  `grupo_id` INT GENERATED ALWAYS AS () VIRTUAL,
  `asignaturaId` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `asignatura_id` INT NOT NULL,
  `Asignaturas_asignatura_id` INT NOT NULL,
  `Profesores_profesores_id` INT NOT NULL,
  PRIMARY KEY (`grupo_id`, `Asignaturas_asignatura_id`, `Profesores_profesores_id`),
  INDEX `fk_Grupos_Asignaturas1_idx` (`Asignaturas_asignatura_id` ASC) VISIBLE,
  INDEX `fk_Grupos_Profesores1_idx` (`Profesores_profesores_id` ASC) VISIBLE,
  CONSTRAINT `fk_Grupos_Asignaturas1`
    FOREIGN KEY (`Asignaturas_asignatura_id`)
    REFERENCES `Escuela`.`Asignaturas` (`asignatura_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grupos_Profesores1`
    FOREIGN KEY (`Profesores_profesores_id`)
    REFERENCES `Escuela`.`Profesores` (`profesores_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escuela`.`Profesores_has_Asignaturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escuela`.`Profesores_has_Asignaturas` (
  `Profesores_profesores_id` INT NOT NULL,
  `Asignaturas_asignatura_id` INT NOT NULL,
  `Departamentos_deparamento_id` INT NOT NULL,
  PRIMARY KEY (`Profesores_profesores_id`, `Asignaturas_asignatura_id`),
  INDEX `fk_Profesores_has_Asignaturas_Asignaturas1_idx` (`Asignaturas_asignatura_id` ASC) VISIBLE,
  INDEX `fk_Profesores_has_Asignaturas_Profesores1_idx` (`Profesores_profesores_id` ASC) VISIBLE,
  INDEX `fk_Profesores_has_Asignaturas_Departamentos1_idx` (`Departamentos_deparamento_id` ASC) VISIBLE,
  CONSTRAINT `fk_Profesores_has_Asignaturas_Profesores1`
    FOREIGN KEY (`Profesores_profesores_id`)
    REFERENCES `Escuela`.`Profesores` (`profesores_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Profesores_has_Asignaturas_Asignaturas1`
    FOREIGN KEY (`Asignaturas_asignatura_id`)
    REFERENCES `Escuela`.`Asignaturas` (`asignatura_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Profesores_has_Asignaturas_Departamentos1`
    FOREIGN KEY (`Departamentos_deparamento_id`)
    REFERENCES `Escuela`.`Departamentos` (`deparamento_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escuela`.`Alumnos_Grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escuela`.`Alumnos_Grupos` (
  `Alumnos_alumnos_id` INT NOT NULL,
  `Grupos_grupo_id` INT NOT NULL,
  `Grupos_Asignaturas_asignatura_id` INT NOT NULL,
  `fecha_Matricula` DATE NULL,
  `calificacion` DECIMAL(2,2) ZEROFILL NULL,
  PRIMARY KEY (`Alumnos_alumnos_id`, `Grupos_grupo_id`, `Grupos_Asignaturas_asignatura_id`),
  INDEX `fk_Alumnos_has_Grupos_Grupos1_idx` (`Grupos_grupo_id` ASC, `Grupos_Asignaturas_asignatura_id` ASC) VISIBLE,
  INDEX `fk_Alumnos_has_Grupos_Alumnos1_idx` (`Alumnos_alumnos_id` ASC) VISIBLE,
  CONSTRAINT `fk_Alumnos_has_Grupos_Alumnos1`
    FOREIGN KEY (`Alumnos_alumnos_id`)
    REFERENCES `Escuela`.`Alumnos` (`alumnos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alumnos_has_Grupos_Grupos1`
    FOREIGN KEY (`Grupos_grupo_id` , `Grupos_Asignaturas_asignatura_id`)
    REFERENCES `Escuela`.`Grupos` (`grupo_id` , `Asignaturas_asignatura_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escuela`.`Aulas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escuela`.`Aulas` (
  `aula_id` INT NOT NULL,
  `capacidad` INT NOT NULL,
  `ubicacion` VARCHAR(45) NULL,
  `Grupos_grupo_id` INT NOT NULL,
  `Grupos_Asignaturas_asignatura_id` INT NOT NULL,
  `Grupos_Profesores_profesores_id` INT NOT NULL,
  PRIMARY KEY (`aula_id`, `Grupos_grupo_id`, `Grupos_Asignaturas_asignatura_id`, `Grupos_Profesores_profesores_id`),
  INDEX `fk_Aulas_Grupos1_idx` (`Grupos_grupo_id` ASC, `Grupos_Asignaturas_asignatura_id` ASC, `Grupos_Profesores_profesores_id` ASC) VISIBLE,
  CONSTRAINT `fk_Aulas_Grupos1`
    FOREIGN KEY (`Grupos_grupo_id` , `Grupos_Asignaturas_asignatura_id` , `Grupos_Profesores_profesores_id`)
    REFERENCES `Escuela`.`Grupos` (`grupo_id` , `Asignaturas_asignatura_id` , `Profesores_profesores_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
